# coding: utf-8

"""
    Tts API

    Description  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_tts
from telestream_cloud_tts.api.tts_api import TtsApi  # noqa: E501
from telestream_cloud_tts.rest import ApiException


class TestTtsApi(unittest.TestCase):
    """TtsApi unit test stubs"""

    def setUp(self):
        self.api = telestream_cloud_tts.api.tts_api.TtsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_corpus(self):
        """Test case for create_corpus

        Creates a new Corpus  # noqa: E501
        """
        pass

    def test_create_job(self):
        """Test case for create_job

        Creates a new Job  # noqa: E501
        """
        pass

    def test_create_project(self):
        """Test case for create_project

        Creates a new Project  # noqa: E501
        """
        pass

    def test_delete_corpus(self):
        """Test case for delete_corpus

        Creates a new Corpus  # noqa: E501
        """
        pass

    def test_delete_job(self):
        """Test case for delete_job

        Deletes the Job  # noqa: E501
        """
        pass

    def test_delete_project(self):
        """Test case for delete_project

        Deletes the Project  # noqa: E501
        """
        pass

    def test_get_job(self):
        """Test case for get_job

        Returns the Job  # noqa: E501
        """
        pass

    def test_get_project(self):
        """Test case for get_project

        Returns the Project  # noqa: E501
        """
        pass

    def test_getget_corpus(self):
        """Test case for getget_corpus

        Returns the Corpus  # noqa: E501
        """
        pass

    def test_job_outputs(self):
        """Test case for job_outputs

        Returns the Job Outputs  # noqa: E501
        """
        pass

    def test_job_result(self):
        """Test case for job_result

        Returns the Job Result  # noqa: E501
        """
        pass

    def test_list_corpora(self):
        """Test case for list_corpora

        Returns a collection of Corpora  # noqa: E501
        """
        pass

    def test_list_jobs(self):
        """Test case for list_jobs

        Returns a collection of Jobs  # noqa: E501
        """
        pass

    def test_list_projects(self):
        """Test case for list_projects

        Returns a collection of Projects  # noqa: E501
        """
        pass

    def test_train_project(self):
        """Test case for train_project

        Queues training  # noqa: E501
        """
        pass

    def test_update_project(self):
        """Test case for update_project

        Updates an existing Project  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
