# coding: utf-8

"""
    Tts API

    Description  # noqa: E501

    The version of the OpenAPI document: 2.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import telestream_cloud_tts
from telestream_cloud_tts.models.project import Project  # noqa: E501
from telestream_cloud_tts.rest import ApiException

class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Project
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = telestream_cloud_tts.models.project.Project()  # noqa: E501
        if include_optional :
            return Project(
                id = 'tg01a16130b9418395e68f844de8ab20', 
                name = 'Example project', 
                description = '0', 
                status = 'available', 
                language = 'en-US', 
                sample_rate = 16000, 
                profanity_filter = True, 
                generate_proxy = True, 
                custom_words = '0', 
                capabilities = [
                    '0'
                    ], 
                created_at = '2017-01-02T03:04:05Z', 
                updated_at = '2017-01-02T03:04:05Z'
            )
        else :
            return Project(
        )

    def testProject(self):
        """Test Project"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
