# coding: utf-8

"""
    Flip API

    Description

    OpenAPI spec version: 3.1.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class CloudNotificationSettings(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'url': 'str',
        'delay': 'int',
        'send_video_payload': 'bool',
        'events': 'CloudNotificationSettingsEvents'
    }

    attribute_map = {
        'url': 'url',
        'delay': 'delay',
        'send_video_payload': 'send_video_payload',
        'events': 'events'
    }

    def __init__(self, url=None, delay=None, send_video_payload=None, events=None):
        """
        CloudNotificationSettings - a model defined in Swagger
        """

        self._url = None
        self._delay = None
        self._send_video_payload = None
        self._events = None

        self.url = url
        self.delay = delay
        self.send_video_payload = send_video_payload
        if events is not None:
          self.events = events

    @property
    def url(self):
        """
        Gets the url of this CloudNotificationSettings.
        Notifications will be sent to this endpoint.

        :return: The url of this CloudNotificationSettings.
        :rtype: str
        """
        return self._url

    @url.setter
    def url(self, url):
        """
        Sets the url of this CloudNotificationSettings.
        Notifications will be sent to this endpoint.

        :param url: The url of this CloudNotificationSettings.
        :type: str
        """
        if url is None:
            raise ValueError("Invalid value for `url`, must not be `None`")

        self._url = url

    @property
    def delay(self):
        """
        Gets the delay of this CloudNotificationSettings.

        :return: The delay of this CloudNotificationSettings.
        :rtype: int
        """
        return self._delay

    @delay.setter
    def delay(self, delay):
        """
        Sets the delay of this CloudNotificationSettings.

        :param delay: The delay of this CloudNotificationSettings.
        :type: int
        """
        if delay is None:
            raise ValueError("Invalid value for `delay`, must not be `None`")

        self._delay = delay

    @property
    def send_video_payload(self):
        """
        Gets the send_video_payload of this CloudNotificationSettings.
        Determines whether a video payload will be included in notification messages.

        :return: The send_video_payload of this CloudNotificationSettings.
        :rtype: bool
        """
        return self._send_video_payload

    @send_video_payload.setter
    def send_video_payload(self, send_video_payload):
        """
        Sets the send_video_payload of this CloudNotificationSettings.
        Determines whether a video payload will be included in notification messages.

        :param send_video_payload: The send_video_payload of this CloudNotificationSettings.
        :type: bool
        """
        if send_video_payload is None:
            raise ValueError("Invalid value for `send_video_payload`, must not be `None`")

        self._send_video_payload = send_video_payload

    @property
    def events(self):
        """
        Gets the events of this CloudNotificationSettings.

        :return: The events of this CloudNotificationSettings.
        :rtype: CloudNotificationSettingsEvents
        """
        return self._events

    @events.setter
    def events(self, events):
        """
        Sets the events of this CloudNotificationSettings.

        :param events: The events of this CloudNotificationSettings.
        :type: CloudNotificationSettingsEvents
        """

        self._events = events

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, CloudNotificationSettings):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
