# coding: utf-8

"""
    Flip API

    Description

    OpenAPI spec version: 3.1.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class ExtraFile(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'tag': 'str',
        'file_size': 'int',
        'file_name': 'str'
    }

    attribute_map = {
        'tag': 'tag',
        'file_size': 'file_size',
        'file_name': 'file_name'
    }

    def __init__(self, tag=None, file_size=None, file_name=None):
        """
        ExtraFile - a model defined in Swagger
        """

        self._tag = None
        self._file_size = None
        self._file_name = None

        if tag is not None:
          self.tag = tag
        if file_size is not None:
          self.file_size = file_size
        if file_name is not None:
          self.file_name = file_name

    @property
    def tag(self):
        """
        Gets the tag of this ExtraFile.

        :return: The tag of this ExtraFile.
        :rtype: str
        """
        return self._tag

    @tag.setter
    def tag(self, tag):
        """
        Sets the tag of this ExtraFile.

        :param tag: The tag of this ExtraFile.
        :type: str
        """

        self._tag = tag

    @property
    def file_size(self):
        """
        Gets the file_size of this ExtraFile.

        :return: The file_size of this ExtraFile.
        :rtype: int
        """
        return self._file_size

    @file_size.setter
    def file_size(self, file_size):
        """
        Sets the file_size of this ExtraFile.

        :param file_size: The file_size of this ExtraFile.
        :type: int
        """

        self._file_size = file_size

    @property
    def file_name(self):
        """
        Gets the file_name of this ExtraFile.

        :return: The file_name of this ExtraFile.
        :rtype: str
        """
        return self._file_name

    @file_name.setter
    def file_name(self, file_name):
        """
        Sets the file_name of this ExtraFile.

        :param file_name: The file_name of this ExtraFile.
        :type: str
        """

        self._file_name = file_name

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, ExtraFile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
