# coding: utf-8

"""
    Flip API

    Description

    OpenAPI spec version: 3.1.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class FactorySync(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'syncing': 'str'
    }

    attribute_map = {
        'syncing': 'syncing'
    }

    def __init__(self, syncing=None):
        """
        FactorySync - a model defined in Swagger
        """

        self._syncing = None

        if syncing is not None:
          self.syncing = syncing

    @property
    def syncing(self):
        """
        Gets the syncing of this FactorySync.
        Determines whether a Factory will be synchronised with an input bucket.

        :return: The syncing of this FactorySync.
        :rtype: str
        """
        return self._syncing

    @syncing.setter
    def syncing(self, syncing):
        """
        Sets the syncing of this FactorySync.
        Determines whether a Factory will be synchronised with an input bucket.

        :param syncing: The syncing of this FactorySync.
        :type: str
        """
        allowed_values = ["starting", "already_started"]
        if syncing not in allowed_values:
            raise ValueError(
                "Invalid value for `syncing` ({0}), must be one of {1}"
                .format(syncing, allowed_values)
            )

        self._syncing = syncing

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, FactorySync):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
