# coding: utf-8

"""
    Flip API

    Description

    OpenAPI spec version: 3.1.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from pprint import pformat
from six import iteritems
import re


class PaginatedProfilesCollection(object):
    """
    NOTE: This class is auto generated by the swagger code generator program.
    Do not edit the class manually.
    """


    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'profiles': 'list[Profile]',
        'page': 'int',
        'per_page': 'int',
        'total': 'int'
    }

    attribute_map = {
        'profiles': 'profiles',
        'page': 'page',
        'per_page': 'per_page',
        'total': 'total'
    }

    def __init__(self, profiles=None, page=None, per_page=None, total=None):
        """
        PaginatedProfilesCollection - a model defined in Swagger
        """

        self._profiles = None
        self._page = None
        self._per_page = None
        self._total = None

        if profiles is not None:
          self.profiles = profiles
        if page is not None:
          self.page = page
        if per_page is not None:
          self.per_page = per_page
        if total is not None:
          self.total = total

    @property
    def profiles(self):
        """
        Gets the profiles of this PaginatedProfilesCollection.

        :return: The profiles of this PaginatedProfilesCollection.
        :rtype: list[Profile]
        """
        return self._profiles

    @profiles.setter
    def profiles(self, profiles):
        """
        Sets the profiles of this PaginatedProfilesCollection.

        :param profiles: The profiles of this PaginatedProfilesCollection.
        :type: list[Profile]
        """

        self._profiles = profiles

    @property
    def page(self):
        """
        Gets the page of this PaginatedProfilesCollection.
        A number of the fetched page.

        :return: The page of this PaginatedProfilesCollection.
        :rtype: int
        """
        return self._page

    @page.setter
    def page(self, page):
        """
        Sets the page of this PaginatedProfilesCollection.
        A number of the fetched page.

        :param page: The page of this PaginatedProfilesCollection.
        :type: int
        """

        self._page = page

    @property
    def per_page(self):
        """
        Gets the per_page of this PaginatedProfilesCollection.
        A number of profiles per page.

        :return: The per_page of this PaginatedProfilesCollection.
        :rtype: int
        """
        return self._per_page

    @per_page.setter
    def per_page(self, per_page):
        """
        Sets the per_page of this PaginatedProfilesCollection.
        A number of profiles per page.

        :param per_page: The per_page of this PaginatedProfilesCollection.
        :type: int
        """

        self._per_page = per_page

    @property
    def total(self):
        """
        Gets the total of this PaginatedProfilesCollection.
        A number of all profiles stored in the db.

        :return: The total of this PaginatedProfilesCollection.
        :rtype: int
        """
        return self._total

    @total.setter
    def total(self, total):
        """
        Sets the total of this PaginatedProfilesCollection.
        A number of all profiles stored in the db.

        :param total: The total of this PaginatedProfilesCollection.
        :type: int
        """

        self._total = total

    def to_dict(self):
        """
        Returns the model properties as a dict
        """
        result = {}

        for attr, _ in iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """
        Returns the string representation of the model
        """
        return pformat(self.to_dict())

    def __repr__(self):
        """
        For `print` and `pprint`
        """
        return self.to_str()

    def __eq__(self, other):
        """
        Returns true if both objects are equal
        """
        if not isinstance(other, PaginatedProfilesCollection):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """
        Returns true if both objects are not equal
        """
        return not self == other
