# coding: utf-8

"""
    Qc API

    QC API

    OpenAPI spec version: 1.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import telestream_cloud_qc
from telestream_cloud_qc.rest import ApiException
from telestream_cloud_qc.models.media import Media


class TestMedia(unittest.TestCase):
    """ Media unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMedia(self):
        """
        Test Media
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = telestream_cloud_qc.models.media.Media()
        pass


if __name__ == '__main__':
    unittest.main()
