# coding: utf-8

"""
    Notifications API

    Notifications API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from telestream_cloud_notifications.models.params import Params  # noqa: F401,E501
from telestream_cloud_notifications.models.topic import Topic  # noqa: F401,E501


class Subscription(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'type': 'str',
        'topic': 'Topic',
        'params': 'Params'
    }

    attribute_map = {
        'id': 'id',
        'type': 'type',
        'topic': 'topic',
        'params': 'params'
    }

    def __init__(self, id=None, type=None, topic=None, params=None):  # noqa: E501
        """Subscription - a model defined in Swagger"""  # noqa: E501

        self._id = None
        self._type = None
        self._topic = None
        self._params = None
        self.discriminator = None

        if id is not None:
            self.id = id
        if type is not None:
            self.type = type
        if topic is not None:
            self.topic = topic
        if params is not None:
            self.params = params

    @property
    def id(self):
        """Gets the id of this Subscription.  # noqa: E501

        [read-only] Subscription identifier   # noqa: E501

        :return: The id of this Subscription.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this Subscription.

        [read-only] Subscription identifier   # noqa: E501

        :param id: The id of this Subscription.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def type(self):
        """Gets the type of this Subscription.  # noqa: E501

        [required] Type of subscription (email, webhook)   # noqa: E501

        :return: The type of this Subscription.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Subscription.

        [required] Type of subscription (email, webhook)   # noqa: E501

        :param type: The type of this Subscription.  # noqa: E501
        :type: str
        """
        allowed_values = ["email", "webhook"]  # noqa: E501
        if type not in allowed_values:
            raise ValueError(
                "Invalid value for `type` ({0}), must be one of {1}"  # noqa: E501
                .format(type, allowed_values)
            )

        self._type = type

    @property
    def topic(self):
        """Gets the topic of this Subscription.  # noqa: E501

        [required]   # noqa: E501

        :return: The topic of this Subscription.  # noqa: E501
        :rtype: Topic
        """
        return self._topic

    @topic.setter
    def topic(self, topic):
        """Sets the topic of this Subscription.

        [required]   # noqa: E501

        :param topic: The topic of this Subscription.  # noqa: E501
        :type: Topic
        """

        self._topic = topic

    @property
    def params(self):
        """Gets the params of this Subscription.  # noqa: E501

        [required]   # noqa: E501

        :return: The params of this Subscription.  # noqa: E501
        :rtype: Params
        """
        return self._params

    @params.setter
    def params(self, params):
        """Sets the params of this Subscription.

        [required]   # noqa: E501

        :param params: The params of this Subscription.  # noqa: E501
        :type: Params
        """

        self._params = params

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Subscription):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
