# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import telestream_cloud_qc
from telestream_cloud_qc.models.as11_xprofile_test import As11XprofileTest  # noqa: E501
from telestream_cloud_qc.rest import ApiException

class TestAs11XprofileTest(unittest.TestCase):
    """As11XprofileTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test As11XprofileTest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = telestream_cloud_qc.models.as11_xprofile_test.As11XprofileTest()  # noqa: E501
        if include_optional :
            return As11XprofileTest(
                as11_rules = telestream_cloud_qc.models.as11_rules.as11_rules(
                    rule = [
                        '0'
                        ], ), 
                embedded_xml_documents = 'EMBEDDED-XML-NONE', 
                extra_audio_layout_modes = 'EXTRA-AUDIO-MODES-NONE', 
                picture_essence_constraints = 'PIC-ESSENCE-CONSTRAINTS-NONE', 
                file_format_specification_identification_label = 'FILE-FORMAT-SPEC-ID-NONE', 
                reject_on_error = True, 
                checked = True
            )
        else :
            return As11XprofileTest(
        )

    def testAs11XprofileTest(self):
        """Test As11XprofileTest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
