# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import telestream_cloud_qc
from telestream_cloud_qc.models.digital_silence_at_start_end_test import DigitalSilenceAtStartEndTest  # noqa: E501
from telestream_cloud_qc.rest import ApiException

class TestDigitalSilenceAtStartEndTest(unittest.TestCase):
    """DigitalSilenceAtStartEndTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test DigitalSilenceAtStartEndTest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = telestream_cloud_qc.models.digital_silence_at_start_end_test.DigitalSilenceAtStartEndTest()  # noqa: E501
        if include_optional :
            return DigitalSilenceAtStartEndTest(
                duration_at_start = 1.337, 
                duration_at_end = 1.337, 
                duration_secs_or_frames = 'Seconds', 
                must_or_must_not_be_silent = 'Must', 
                channels = telestream_cloud_qc.models.channels.channels(
                    channel = [
                        True
                        ], ), 
                reject_on_error = True, 
                do_correction = True, 
                checked = True
            )
        else :
            return DigitalSilenceAtStartEndTest(
        )

    def testDigitalSilenceAtStartEndTest(self):
        """Test DigitalSilenceAtStartEndTest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
