# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import telestream_cloud_qc
from telestream_cloud_qc.models.project import Project  # noqa: E501
from telestream_cloud_qc.rest import ApiException

class TestProject(unittest.TestCase):
    """Project unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Project
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = telestream_cloud_qc.models.project.Project()  # noqa: E501
        if include_optional :
            return Project(
                id = '0', 
                name = '0', 
                status = 'active', 
                template = '0', 
                options = {"file_tests":{"container_test":{"checked":true,"container":"Mov","reject_on_error":true},"video_codec_test":{"checked":true,"video_codec":"ProRes","video_profile":"VideoProfileNone","video_level":"VideoLevelNone","reject_on_error":true},"container_essence_consistency_test":{"checked":true},"enhanced_syntax_test":{"checked":true},"framesize_test":{"checked":true,"horizontal_size":1920,"vertical_size":1080},"pixel_aspect_ratio_test":{"checked":true,"pixel_aspect_ratio_numerator":1,"pixel_aspect_ratio_denominator":1},"i_tunes_compatibility_test":{"checked":true,"reject_on_error":true},"framerate_test":{"checked":true,"framerate_numerator":25,"framerate_denominator":1},"video_bit_rate_mode_test":{"checked":true,"mode":"VBR"},"video_bitrate_test":{"checked":true,"video_bitrate_lower":88,"video_bitrate_upper":220}}}
            )
        else :
            return Project(
        )

    def testProject(self):
        """Test Project"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
