# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import telestream_cloud_qc
from telestream_cloud_qc.models.chroma_level_test import ChromaLevelTest  # noqa: E501
from telestream_cloud_qc.rest import ApiException

class TestChromaLevelTest(unittest.TestCase):
    """ChromaLevelTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ChromaLevelTest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = telestream_cloud_qc.models.chroma_level_test.ChromaLevelTest()  # noqa: E501
        if include_optional :
            return ChromaLevelTest(
                y_level_default_or_custom = 'Default', 
                y_level_lower = 56, 
                y_level_upper = 56, 
                y_level_max_outside_range = 1.337, 
                y_level_tolerance_low = 1.337, 
                y_level_tolerance_high = 1.337, 
                u_vlevel_default_or_custom = 'Default', 
                u_vlevel_lower = 56, 
                u_vlevel_upper = 56, 
                u_vlevel_max_outside_range = 1.337, 
                low_pass_filter = 'NoFilter', 
                reject_on_error = True, 
                do_correction = True, 
                checked = True
            )
        else :
            return ChromaLevelTest(
        )

    def testChromaLevelTest(self):
        """Test ChromaLevelTest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
