# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import telestream_cloud_qc
from telestream_cloud_qc.models.blockiness_test import BlockinessTest  # noqa: E501
from telestream_cloud_qc.rest import ApiException

class TestBlockinessTest(unittest.TestCase):
    """BlockinessTest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test BlockinessTest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = telestream_cloud_qc.models.blockiness_test.BlockinessTest()  # noqa: E501
        if include_optional :
            return BlockinessTest(
                quality_level = 56, 
                max_time_below_quality = 1.337, 
                max_time_below_quality_secs_or_frames = 'Seconds', 
                reject_on_error = True, 
                checked = True
            )
        else :
            return BlockinessTest(
        )

    def testBlockinessTest(self):
        """Test BlockinessTest"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
