# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from telestream_cloud_qc.configuration import Configuration


class AvcSpsPpsTest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'profile': 'int',
        'profile_constraint': 'int',
        'sps_flag': 'int',
        'pps_flag': 'int',
        'level': 'int',
        'reject_on_error': 'bool',
        'checked': 'bool'
    }

    attribute_map = {
        'profile': 'profile',
        'profile_constraint': 'profile_constraint',
        'sps_flag': 'sps_flag',
        'pps_flag': 'pps_flag',
        'level': 'level',
        'reject_on_error': 'reject_on_error',
        'checked': 'checked'
    }

    def __init__(self, profile=None, profile_constraint=None, sps_flag=None, pps_flag=None, level=None, reject_on_error=None, checked=None, local_vars_configuration=None):  # noqa: E501
        """AvcSpsPpsTest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._profile = None
        self._profile_constraint = None
        self._sps_flag = None
        self._pps_flag = None
        self._level = None
        self._reject_on_error = None
        self._checked = None
        self.discriminator = None

        if profile is not None:
            self.profile = profile
        if profile_constraint is not None:
            self.profile_constraint = profile_constraint
        if sps_flag is not None:
            self.sps_flag = sps_flag
        if pps_flag is not None:
            self.pps_flag = pps_flag
        if level is not None:
            self.level = level
        if reject_on_error is not None:
            self.reject_on_error = reject_on_error
        if checked is not None:
            self.checked = checked

    @property
    def profile(self):
        """Gets the profile of this AvcSpsPpsTest.  # noqa: E501


        :return: The profile of this AvcSpsPpsTest.  # noqa: E501
        :rtype: int
        """
        return self._profile

    @profile.setter
    def profile(self, profile):
        """Sets the profile of this AvcSpsPpsTest.


        :param profile: The profile of this AvcSpsPpsTest.  # noqa: E501
        :type: int
        """

        self._profile = profile

    @property
    def profile_constraint(self):
        """Gets the profile_constraint of this AvcSpsPpsTest.  # noqa: E501


        :return: The profile_constraint of this AvcSpsPpsTest.  # noqa: E501
        :rtype: int
        """
        return self._profile_constraint

    @profile_constraint.setter
    def profile_constraint(self, profile_constraint):
        """Sets the profile_constraint of this AvcSpsPpsTest.


        :param profile_constraint: The profile_constraint of this AvcSpsPpsTest.  # noqa: E501
        :type: int
        """

        self._profile_constraint = profile_constraint

    @property
    def sps_flag(self):
        """Gets the sps_flag of this AvcSpsPpsTest.  # noqa: E501


        :return: The sps_flag of this AvcSpsPpsTest.  # noqa: E501
        :rtype: int
        """
        return self._sps_flag

    @sps_flag.setter
    def sps_flag(self, sps_flag):
        """Sets the sps_flag of this AvcSpsPpsTest.


        :param sps_flag: The sps_flag of this AvcSpsPpsTest.  # noqa: E501
        :type: int
        """

        self._sps_flag = sps_flag

    @property
    def pps_flag(self):
        """Gets the pps_flag of this AvcSpsPpsTest.  # noqa: E501


        :return: The pps_flag of this AvcSpsPpsTest.  # noqa: E501
        :rtype: int
        """
        return self._pps_flag

    @pps_flag.setter
    def pps_flag(self, pps_flag):
        """Sets the pps_flag of this AvcSpsPpsTest.


        :param pps_flag: The pps_flag of this AvcSpsPpsTest.  # noqa: E501
        :type: int
        """

        self._pps_flag = pps_flag

    @property
    def level(self):
        """Gets the level of this AvcSpsPpsTest.  # noqa: E501


        :return: The level of this AvcSpsPpsTest.  # noqa: E501
        :rtype: int
        """
        return self._level

    @level.setter
    def level(self, level):
        """Sets the level of this AvcSpsPpsTest.


        :param level: The level of this AvcSpsPpsTest.  # noqa: E501
        :type: int
        """

        self._level = level

    @property
    def reject_on_error(self):
        """Gets the reject_on_error of this AvcSpsPpsTest.  # noqa: E501


        :return: The reject_on_error of this AvcSpsPpsTest.  # noqa: E501
        :rtype: bool
        """
        return self._reject_on_error

    @reject_on_error.setter
    def reject_on_error(self, reject_on_error):
        """Sets the reject_on_error of this AvcSpsPpsTest.


        :param reject_on_error: The reject_on_error of this AvcSpsPpsTest.  # noqa: E501
        :type: bool
        """

        self._reject_on_error = reject_on_error

    @property
    def checked(self):
        """Gets the checked of this AvcSpsPpsTest.  # noqa: E501


        :return: The checked of this AvcSpsPpsTest.  # noqa: E501
        :rtype: bool
        """
        return self._checked

    @checked.setter
    def checked(self, checked):
        """Sets the checked of this AvcSpsPpsTest.


        :param checked: The checked of this AvcSpsPpsTest.  # noqa: E501
        :type: bool
        """

        self._checked = checked

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AvcSpsPpsTest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AvcSpsPpsTest):
            return True

        return self.to_dict() != other.to_dict()
