# coding: utf-8

"""
    Qc API

    Qc API  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from telestream_cloud_qc.configuration import Configuration


class FieldOrderTest(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'flagged_field_order': 'FieldOrderType',
        'baseband_enabled': 'bool',
        'simple': 'bool',
        'baseband_field_order': 'FieldOrderType',
        'reject_on_error': 'bool',
        'checked': 'bool'
    }

    attribute_map = {
        'flagged_field_order': 'flagged_field_order',
        'baseband_enabled': 'baseband_enabled',
        'simple': 'simple',
        'baseband_field_order': 'baseband_field_order',
        'reject_on_error': 'reject_on_error',
        'checked': 'checked'
    }

    def __init__(self, flagged_field_order=None, baseband_enabled=None, simple=None, baseband_field_order=None, reject_on_error=None, checked=None, local_vars_configuration=None):  # noqa: E501
        """FieldOrderTest - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._flagged_field_order = None
        self._baseband_enabled = None
        self._simple = None
        self._baseband_field_order = None
        self._reject_on_error = None
        self._checked = None
        self.discriminator = None

        if flagged_field_order is not None:
            self.flagged_field_order = flagged_field_order
        if baseband_enabled is not None:
            self.baseband_enabled = baseband_enabled
        if simple is not None:
            self.simple = simple
        if baseband_field_order is not None:
            self.baseband_field_order = baseband_field_order
        if reject_on_error is not None:
            self.reject_on_error = reject_on_error
        if checked is not None:
            self.checked = checked

    @property
    def flagged_field_order(self):
        """Gets the flagged_field_order of this FieldOrderTest.  # noqa: E501


        :return: The flagged_field_order of this FieldOrderTest.  # noqa: E501
        :rtype: FieldOrderType
        """
        return self._flagged_field_order

    @flagged_field_order.setter
    def flagged_field_order(self, flagged_field_order):
        """Sets the flagged_field_order of this FieldOrderTest.


        :param flagged_field_order: The flagged_field_order of this FieldOrderTest.  # noqa: E501
        :type: FieldOrderType
        """

        self._flagged_field_order = flagged_field_order

    @property
    def baseband_enabled(self):
        """Gets the baseband_enabled of this FieldOrderTest.  # noqa: E501


        :return: The baseband_enabled of this FieldOrderTest.  # noqa: E501
        :rtype: bool
        """
        return self._baseband_enabled

    @baseband_enabled.setter
    def baseband_enabled(self, baseband_enabled):
        """Sets the baseband_enabled of this FieldOrderTest.


        :param baseband_enabled: The baseband_enabled of this FieldOrderTest.  # noqa: E501
        :type: bool
        """

        self._baseband_enabled = baseband_enabled

    @property
    def simple(self):
        """Gets the simple of this FieldOrderTest.  # noqa: E501


        :return: The simple of this FieldOrderTest.  # noqa: E501
        :rtype: bool
        """
        return self._simple

    @simple.setter
    def simple(self, simple):
        """Sets the simple of this FieldOrderTest.


        :param simple: The simple of this FieldOrderTest.  # noqa: E501
        :type: bool
        """

        self._simple = simple

    @property
    def baseband_field_order(self):
        """Gets the baseband_field_order of this FieldOrderTest.  # noqa: E501


        :return: The baseband_field_order of this FieldOrderTest.  # noqa: E501
        :rtype: FieldOrderType
        """
        return self._baseband_field_order

    @baseband_field_order.setter
    def baseband_field_order(self, baseband_field_order):
        """Sets the baseband_field_order of this FieldOrderTest.


        :param baseband_field_order: The baseband_field_order of this FieldOrderTest.  # noqa: E501
        :type: FieldOrderType
        """

        self._baseband_field_order = baseband_field_order

    @property
    def reject_on_error(self):
        """Gets the reject_on_error of this FieldOrderTest.  # noqa: E501


        :return: The reject_on_error of this FieldOrderTest.  # noqa: E501
        :rtype: bool
        """
        return self._reject_on_error

    @reject_on_error.setter
    def reject_on_error(self, reject_on_error):
        """Sets the reject_on_error of this FieldOrderTest.


        :param reject_on_error: The reject_on_error of this FieldOrderTest.  # noqa: E501
        :type: bool
        """

        self._reject_on_error = reject_on_error

    @property
    def checked(self):
        """Gets the checked of this FieldOrderTest.  # noqa: E501


        :return: The checked of this FieldOrderTest.  # noqa: E501
        :rtype: bool
        """
        return self._checked

    @checked.setter
    def checked(self, checked):
        """Sets the checked of this FieldOrderTest.


        :param checked: The checked of this FieldOrderTest.  # noqa: E501
        :type: bool
        """

        self._checked = checked

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, FieldOrderTest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, FieldOrderTest):
            return True

        return self.to_dict() != other.to_dict()
