# coding: utf-8

"""
    Flip API

    Description

    OpenAPI spec version: 3.1.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import telestream_cloud_flip
from telestream_cloud_flip.rest import ApiException
from telestream_cloud_flip.models.paginated_encodings_collection import PaginatedEncodingsCollection


class TestPaginatedEncodingsCollection(unittest.TestCase):
    """ PaginatedEncodingsCollection unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedEncodingsCollection(self):
        """
        Test PaginatedEncodingsCollection
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = telestream_cloud_flip.models.paginated_encodings_collection.PaginatedEncodingsCollection()
        pass


if __name__ == '__main__':
    unittest.main()
