# coding: utf-8

"""
    Flip API

    Description

    OpenAPI spec version: 3.1.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import telestream_cloud_flip
from telestream_cloud_flip.rest import ApiException
from telestream_cloud_flip.models.signed_video_url import SignedVideoUrl


class TestSignedVideoUrl(unittest.TestCase):
    """ SignedVideoUrl unit test stubs """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSignedVideoUrl(self):
        """
        Test SignedVideoUrl
        """
        # FIXME: construct object with mandatory attributes with example values
        #model = telestream_cloud_flip.models.signed_video_url.SignedVideoUrl()
        pass


if __name__ == '__main__':
    unittest.main()
