# coding: utf-8

"""
    Notifications API

    Notifications API  # noqa: E501

    OpenAPI spec version: 2.0.0
    Contact: cloudsupport@telestream.net
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_notifications
from telestream_cloud_notifications.models.subscription import Subscription  # noqa: E501
from telestream_cloud_notifications.rest import ApiException


class TestSubscription(unittest.TestCase):
    """Subscription unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSubscription(self):
        """Test Subscription"""
        # FIXME: construct object with mandatory attributes with example values
        # model = telestream_cloud_notifications.models.subscription.Subscription()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
